### ISSUE TITLE
Flask Discord create bot invite?

### ISSUE THREAD

**Issue by RedstonedLife** [thec0sm0s/Flask-Discord#4]
Can the feature of creating invites using flask-discord be added?
Cause discord redirect URI is broken when you use the discord developer portal.

**Comment by thec0sm0s** [comment]
Are you sure you passed the correct list of scopes to `.create_session` method? I tried it myself and the redirect URI works perfectly fine when I pass `["bot"]` to `.create_session` as `discord.create_session(["bot"])` to make redirect URI work like your bot invite URL.

Though obviously there will be no permissions argument present in the redirect URI so the invite URL is returned without any permissions since redirect URI is generalized property.

I might look forward to include support for bot's invite with permissions builder class. But for now you can use `discord.create_session(["bot])`.
